# Generated by Django 4.2.14 on 2024-07-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('PRO', 'Proton'), ('PER', 'Perodua'), ('HON', 'Honda'), ('TOY', 'Toyota'), ('NIS', 'Nissan'), ('MAZ', 'Mazda'), ('BMW', 'BMW'), ('MER', 'Mercedes-Benz'), ('AUD', 'Audi'), ('VOL', 'Volkswagen'), ('HYU', 'Hyundai'), ('KIA', 'Kia'), ('FOR', 'Ford'), ('CHE', 'Chevrolet'), ('SUB', 'Subaru'), ('POR', 'Porsche'), ('LEX', 'Lexus'), ('JAG', 'Jaguar'), ('LR', 'Land Rover'), ('MIT', 'Mitsubishi'), ('PEU', 'Peugeot'), ('REN', 'Renault'), ('SUZ', 'Suzuki')], max_length=10)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('repairing', 'Repairing')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.car')),
            ],
        ),
    ]
